### ISSUE TITLE
【Feature Request】extra_group can use other extra_groups as it's outbounds

### ISSUE THREAD

**Issue by ningzio** [SagerNet/serenity#36]
I defined some extra_groups base on territory, like HK, USA...

I want to use different territory on different site, like openAI, I'd like use USA, but HK. 

currently, extra_groups can only use "servers" getting from subscription

I don't know how to do this, I've read the documents, and the code.

```
- tag: "HK",
  outbounds:
    - "HK nodes"
    - "..."

- tag: "US"
  outbounds:
    - "US nodes"
    - "..."

- tag: "OpenAI"
  outbounds:
    - US
```
